/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SectionType = IDL.Variant({
  'education' : IDL.Null,
  'experience' : IDL.Null,
  'summary' : IDL.Null,
  'skills' : IDL.Null,
});
export const UpdateSection = IDL.Tuple(SectionType, IDL.Text);
export const Resume = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'sections' : IDL.Vec(IDL.Tuple(SectionType, IDL.Text)),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const SuggestionCategory = IDL.Variant({
  'impact' : IDL.Null,
  'formatting' : IDL.Null,
  'clarity' : IDL.Null,
  'keywords' : IDL.Null,
});
export const Suggestion = IDL.Record({
  'section' : SectionType,
  'message' : IDL.Text,
  'category' : SuggestionCategory,
});
export const Time = IDL.Int;
export const CoachingResult = IDL.Record({
  'suggestions' : IDL.Vec(Suggestion),
  'timestamp' : Time,
});
export const ResumeWithCoaching = IDL.Record({
  'resume' : Resume,
  'coaching' : IDL.Opt(CoachingResult),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createResume' : IDL.Func([IDL.Text, IDL.Vec(UpdateSection)], [IDL.Nat], []),
  'deleteResume' : IDL.Func([IDL.Nat], [], []),
  'getAllResumes' : IDL.Func([], [IDL.Vec(Resume)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCoachingResult' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(CoachingResult)],
      ['query'],
    ),
  'getResume' : IDL.Func([IDL.Nat], [Resume], ['query']),
  'getResumeWithCoaching' : IDL.Func(
      [IDL.Nat],
      [ResumeWithCoaching],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'runCoaching' : IDL.Func([IDL.Nat], [CoachingResult], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateResume' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Vec(UpdateSection)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SectionType = IDL.Variant({
    'education' : IDL.Null,
    'experience' : IDL.Null,
    'summary' : IDL.Null,
    'skills' : IDL.Null,
  });
  const UpdateSection = IDL.Tuple(SectionType, IDL.Text);
  const Resume = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'sections' : IDL.Vec(IDL.Tuple(SectionType, IDL.Text)),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const SuggestionCategory = IDL.Variant({
    'impact' : IDL.Null,
    'formatting' : IDL.Null,
    'clarity' : IDL.Null,
    'keywords' : IDL.Null,
  });
  const Suggestion = IDL.Record({
    'section' : SectionType,
    'message' : IDL.Text,
    'category' : SuggestionCategory,
  });
  const Time = IDL.Int;
  const CoachingResult = IDL.Record({
    'suggestions' : IDL.Vec(Suggestion),
    'timestamp' : Time,
  });
  const ResumeWithCoaching = IDL.Record({
    'resume' : Resume,
    'coaching' : IDL.Opt(CoachingResult),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createResume' : IDL.Func(
        [IDL.Text, IDL.Vec(UpdateSection)],
        [IDL.Nat],
        [],
      ),
    'deleteResume' : IDL.Func([IDL.Nat], [], []),
    'getAllResumes' : IDL.Func([], [IDL.Vec(Resume)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCoachingResult' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(CoachingResult)],
        ['query'],
      ),
    'getResume' : IDL.Func([IDL.Nat], [Resume], ['query']),
    'getResumeWithCoaching' : IDL.Func(
        [IDL.Nat],
        [ResumeWithCoaching],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'runCoaching' : IDL.Func([IDL.Nat], [CoachingResult], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateResume' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Vec(UpdateSection)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };