/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CoachingResult {
  'suggestions' : Array<Suggestion>,
  'timestamp' : Time,
}
export interface Resume {
  'id' : bigint,
  'title' : string,
  'sections' : Array<[SectionType, string]>,
}
export interface ResumeWithCoaching {
  'resume' : Resume,
  'coaching' : [] | [CoachingResult],
}
export type SectionType = { 'education' : null } |
  { 'experience' : null } |
  { 'summary' : null } |
  { 'skills' : null };
export interface Suggestion {
  'section' : SectionType,
  'message' : string,
  'category' : SuggestionCategory,
}
export type SuggestionCategory = { 'impact' : null } |
  { 'formatting' : null } |
  { 'clarity' : null } |
  { 'keywords' : null };
export type Time = bigint;
export type UpdateSection = [SectionType, string];
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createResume' : ActorMethod<[string, Array<UpdateSection>], bigint>,
  'deleteResume' : ActorMethod<[bigint], undefined>,
  'getAllResumes' : ActorMethod<[], Array<Resume>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCoachingResult' : ActorMethod<[bigint], [] | [CoachingResult]>,
  'getResume' : ActorMethod<[bigint], Resume>,
  'getResumeWithCoaching' : ActorMethod<[bigint], ResumeWithCoaching>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'runCoaching' : ActorMethod<[bigint], CoachingResult>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateResume' : ActorMethod<
    [bigint, string, Array<UpdateSection>],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];